SELECT "sfdc_voc"."account_c" AS "account_c",
  "sfdc opportunities"."account_id" AS "account_id",
  "sfdc opportunities"."add_company_tag_c" AS "add_company_tag_c",
  "sfdc opportunities"."add_use_cases_c" AS "add_use_cases_c",
  "sfdc opportunities"."admin_churn_fc_override_c" AS "admin_churn_fc_override_c",
  "sfdc opportunities"."agenda_c" AS "agenda_c",
  "sfdc opportunities"."amount" AS "amount",
  "sfdc opportunities"."arr_c" AS "arr_c",
  "sfdc opportunities"."authority_c" AS "authority_c",
  "sfdc opportunities"."authority_detail_c" AS "authority_detail_c",
  "sfdc opportunities"."autorenewal_c" AS "autorenewal_c",
  "sfdc opportunities"."average_contract_value_acv_c" AS "average_contract_value_acv_c",
  "sfdc opportunities"."billing_entity_c" AS "billing_entity_c",
  "sfdc opportunities"."budget_in_usd_c" AS "budget_in_usd_c",
  "sfdc opportunities"."business_goals_notes_c" AS "business_goals_notes_c",
  "sfdc opportunities"."campaign_id" AS "campaign_id",
  "sfdc opportunities"."churn_acv_c" AS "churn_acv_c",
  "sfdc opportunities"."churn_arr_c" AS "churn_arr_c",
  "sfdc opportunities"."churn_code_c" AS "churn_code_c",
  "sfdc opportunities"."churn_sub_code_c" AS "churn_sub_code_c",
  "sfdc opportunities"."close_date" AS "close_date",
  "sfdc opportunities"."commit_flag_c" AS "commit_flag_c",
  "sfdc opportunities"."compelling_event_c" AS "compelling_event_c",
  "sfdc opportunities"."confirm_enterprise_requirements_c" AS "confirm_enterprise_requirements_c",
  "sfdc opportunities"."contract_signed_c" AS "contract_signed_c",
  "sfdc opportunities"."contracted_expansion_c" AS "contracted_expansion_c",
  "sfdc opportunities"."contraction_acv_c" AS "contraction_acv_c",
  "sfdc opportunities"."country_c" AS "country_c",
  "sfdc opportunities"."created_by_id" AS "created_by_id (custom_sql_query1)",
  "sfdc_voc"."created_by_id" AS "created_by_id",
  "sfdc_voc"."created_by_role_c" AS "created_by_role_c (custom_sql_query)",
  "sfdc opportunities"."created_by_role_c" AS "created_by_role_c",
  "sfdc opportunities"."created_date" AS "created_date (custom_sql_query1)",
  "sfdc_voc"."created_date" AS "created_date",
  "sfdc opportunities"."csm_c" AS "csm_c",
  "sfdc opportunities"."customer_presentation_date_c" AS "customer_presentation_date_c",
  "sfdc_voc"."customer_story_c" AS "customer_story_c",
  "sfdc opportunities"."customer_value_prop_c" AS "customer_value_prop_c",
  "sfdc opportunities"."department_c" AS "department_c",
  "sfdc opportunities"."dt" AS "dt (custom_sql_query1)",
  CAST("sfdc_voc"."dt" AS TIMESTAMP) AS "dt",
  "sfdc opportunities"."economic_buyer_identified_c" AS "economic_buyer_identified_c",
  "sfdc opportunities"."effective_date_c" AS "effective_date_c",
  "sfdc opportunities"."effective_date_mgr_c" AS "effective_date_mgr_c",
  "sfdc opportunities"."effective_date_vp_c" AS "effective_date_vp_c",
  "sfdc opportunities"."estimated_annual_revenue_c" AS "estimated_annual_revenue_c",
  "sfdc opportunities"."exit_arr_c" AS "exit_arr_c",
  "sfdc opportunities"."expected_close_date_c" AS "expected_close_date_c",
  "sfdc opportunities"."expected_launch_date_c" AS "expected_launch_date_c",
  "sfdc opportunities"."final_confirmation_on_triptik_c" AS "final_confirmation_on_triptik_c",
  "sfdc opportunities"."final_documents_sent_c" AS "final_documents_sent_c",
  "sfdc opportunities"."forecast_category" AS "forecast_category",
  "sfdc opportunities"."forecast_category_name" AS "forecast_category_name",
  "sfdc opportunities"."forecasted_churn_reportable_c" AS "forecasted_churn_reportable_c",
  "sfdc_voc"."function_c" AS "function_c",
  "sfdc opportunities"."gclid_c" AS "gclid_c",
  "sfdc opportunities"."gclid_date_c" AS "gclid_date_c",
  "sfdc_voc"."github_issue_ticket_c" AS "github_issue_ticket_c",
  "sfdc opportunities"."github_ticket_c" AS "github_ticket_c",
  "sfdc.users"."id" AS "id (custom_sql_query)",
  "sfdc opportunities"."id" AS "id (custom_sql_query1)",
  "sfdc_voc"."id" AS "id",
  "sfdc_voc"."if_function_other_enter_reason_here_c" AS "if_function_other_enter_reason_here_c",
  "sfdc_voc"."impact_c" AS "impact_c",
  "sfdc_voc"."in_product_catalog_c" AS "in_product_catalog_c",
  "sfdc opportunities"."inbound_message_c" AS "inbound_message_c",
  "sfdc opportunities"."interested_in_c" AS "interested_in_c",
  "sfdc opportunities"."is_closed" AS "is_closed",
  "sfdc opportunities"."is_deleted" AS "is_deleted (custom_sql_query1)",
  "sfdc_voc"."is_deleted" AS "is_deleted",
  "sfdc_voc"."is_roadmap_c" AS "is_roadmap_c",
  "sfdc opportunities"."is_split" AS "is_split",
  "sfdc opportunities"."is_won" AS "is_won",
  "sfdc opportunities"."last_activity_date" AS "last_activity_date",
  "sfdc_voc"."last_modified_by_id" AS "last_modified_by_id",
  "sfdc opportunities"."last_modified_date" AS "last_modified_date (custom_sql_query1)",
  "sfdc_voc"."last_modified_date" AS "last_modified_date",
  "sfdc opportunities"."last_referenced_date" AS "last_referenced_date (custom_sql_query1)",
  "sfdc_voc"."last_referenced_date" AS "last_referenced_date",
  "sfdc opportunities"."last_trip_tik_update_c" AS "last_trip_tik_update_c",
  "sfdc_voc"."last_viewed_date" AS "last_viewed_date",
  "sfdc opportunities"."latest_hand_off_date_c" AS "latest_hand_off_date_c",
  "sfdc_voc"."lead_c" AS "lead_c",
  "sfdc opportunities"."lead_source" AS "lead_source",
  "sfdc opportunities"."lead_source_detail_c" AS "lead_source_detail_c",
  "sfdc opportunities"."lost_because_c" AS "lost_because_c",
  "sfdc opportunities"."lost_because_competitor_list_c" AS "lost_because_competitor_list_c",
  "sfdc opportunities"."lost_because_detail_c" AS "lost_because_detail_c",
  "sfdc opportunities"."lost_because_notes_c" AS "lost_because_notes_c",
  "sfdc opportunities"."lost_date_c" AS "lost_date_c",
  "sfdc opportunities"."mapbox_service_owner_c" AS "mapbox_service_owner_c",
  "sfdc opportunities"."mapbox_username_c" AS "mapbox_username_c",
  "sfdc opportunities"."name" AS "name (custom_sql_query1)",
  "sfdc_voc"."name" AS "name",
  "sfdc opportunities"."need_detail_c" AS "need_detail_c",
  "sfdc opportunities"."need_notes_sdr_c" AS "need_notes_sdr_c",
  "sfdc opportunities"."need_sdr_c" AS "need_sdr_c",
  "sfdc opportunities"."net_new_arr_c" AS "net_new_arr_c",
  "sfdc opportunities"."net_new_arr_forecast_c" AS "net_new_arr_forecast_c",
  "sfdc opportunities"."net_new_arr_forecast_mgr_c" AS "net_new_arr_forecast_mgr_c",
  "sfdc opportunities"."net_new_arr_forecast_vp_c" AS "net_new_arr_forecast_vp_c",
  "sfdc opportunities"."netsuite_conn_bill_to_tier_c" AS "netsuite_conn_bill_to_tier_c",
  "sfdc opportunities"."netsuite_conn_current_sales_order_id_c" AS "netsuite_conn_current_sales_order_id_c",
  "sfdc opportunities"."netsuite_conn_netsuite_sales_order_number_c" AS "netsuite_conn_netsuite_sales_order_number_c",
  "sfdc opportunities"."netsuite_conn_ship_to_tier_c" AS "netsuite_conn_ship_to_tier_c",
  "sfdc opportunities"."new_acv2019_c" AS "new_acv2019_c",
  "sfdc opportunities"."next_step" AS "next_step",
  "sfdc opportunities"."next_step_c" AS "next_step_c",
  "sfdc opportunities"."next_step_date_c" AS "next_step_date_c",
  "sfdc opportunities"."next_steps_new_c" AS "next_steps_new_c",
  "sfdc opportunities"."non_enterprise_c" AS "non_enterprise_c",
  "sfdc opportunities"."notes_c" AS "notes_c",
  "sfdc opportunities"."objectives_c" AS "objectives_c",
  "sfdc opportunities"."opp_renewal_risk_c" AS "opp_renewal_risk_c",
  "sfdc opportunities"."opp_renewal_risk_flag_c" AS "opp_renewal_risk_flag_c",
  "sfdc_voc"."opportunity_c" AS "opportunity_c",
  "sfdc opportunities"."opportunity_count_c" AS "opportunity_count_c",
  "sfdc opportunities"."opportunity_owner_id_c" AS "opportunity_owner_id_c",
  "sfdc opportunities"."opportunity_product_lines_c" AS "opportunity_product_lines_c",
  "sfdc opportunities"."opportunity_segment_c" AS "opportunity_segment_c",
  "sfdc opportunities"."original_renewal_date_c" AS "original_renewal_date_c",
  "sfdc opportunities"."other_use_case_c" AS "other_use_case_c",
  "sfdc opportunities"."owner_id" AS "owner_id (custom_sql_query1)",
  "sfdc_voc"."owner_id" AS "owner_id",
  "sfdc opportunities"."owner_role_c" AS "owner_role_c",
  "sfdc opportunities"."partner_reseller_c" AS "partner_reseller_c",
  "sfdc opportunities"."poc_kick_off_date_c" AS "poc_kick_off_date_c",
  "sfdc opportunities"."pricebook_2_id" AS "pricebook_2_id",
  "sfdc opportunities"."primary_competitor_c" AS "primary_competitor_c",
  "sfdc opportunities"."primary_use_case_c" AS "primary_use_case_c",
  "sfdc opportunities"."primary_use_case_sdr_c" AS "primary_use_case_sdr_c",
  "sfdc opportunities"."prior_amount_c" AS "prior_amount_c",
  "sfdc opportunities"."prior_close_date_c" AS "prior_close_date_c",
  "sfdc opportunities"."prior_opportunity_c" AS "prior_opportunity_c",
  "sfdc opportunities"."prior_opportunity_service_end_date_c" AS "prior_opportunity_service_end_date_c",
  "sfdc opportunities"."prior_stage_c" AS "prior_stage_c",
  "sfdc opportunities"."probability" AS "probability",
  "sfdc opportunities"."product_acv_c" AS "product_acv_c",
  "sfdc_voc"."product_c" AS "product_c",
  "sfdc_voc"."product_secondary_c" AS "product_secondary_c",
  "sfdc opportunities"."qualified_by_c" AS "qualified_by_c",
  "sfdc opportunities"."record_type_id" AS "record_type_id",
  "sfdc_voc"."remarks_max_255_char_c" AS "remarks_max_255_char_c",
  "sfdc opportunities"."renewal_acv_c" AS "renewal_acv_c",
  "sfdc opportunities"."renewal_arr_c" AS "renewal_arr_c",
  "sfdc opportunities"."renewal_arr_override_c" AS "renewal_arr_override_c",
  "sfdc opportunities"."renewal_deadline_c" AS "renewal_deadline_c",
  "sfdc opportunities"."renewal_health_c" AS "renewal_health_c",
  "sfdc opportunities"."renewal_manager_c" AS "renewal_manager_c",
  "sfdc opportunities"."renewal_new_agreement_c" AS "renewal_new_agreement_c",
  "sfdc opportunities"."requires_legal_c" AS "requires_legal_c",
  "sfdc opportunities"."sal_date_c" AS "sal_date_c",
  "sfdc opportunities"."sales_engineer_c" AS "sales_engineer_c",
  "sfdc opportunities"."sales_forecast_mgr_c" AS "sales_forecast_mgr_c",
  "sfdc opportunities"."sales_forecast_vp_c" AS "sales_forecast_vp_c",
  "sfdc opportunities"."sales_manager_forecast_last_updated_on_c" AS "sales_manager_forecast_last_updated_on_c",
  "sfdc opportunities"."sales_manager_forecast_updated_manually_c" AS "sales_manager_forecast_updated_manually_c",
  "sfdc opportunities"."sales_rep_forecast_last_updated_on_c" AS "sales_rep_forecast_last_updated_on_c",
  "sfdc opportunities"."sales_to_cs_hand_off_c" AS "sales_to_cs_hand_off_c",
  "sfdc opportunities"."se_github_ticket_c" AS "se_github_ticket_c",
  "sfdc opportunities"."service_days_c" AS "service_days_c",
  "sfdc opportunities"."service_end_date_c" AS "service_end_date_c",
  "sfdc opportunities"."service_start_date_c" AS "service_start_date_c",
  "sfdc opportunities"."service_years_c" AS "service_years_c",
  "sfdc opportunities"."shipping_entity_c" AS "shipping_entity_c",
  "sfdc opportunities"."stage_0_date_c" AS "stage_0_date_c",
  "sfdc opportunities"."stage_1_date_c" AS "stage_1_date_c",
  "sfdc opportunities"."stage_2_date_c" AS "stage_2_date_c",
  "sfdc opportunities"."stage_3_date_c" AS "stage_3_date_c",
  "sfdc opportunities"."stage_4_date_c" AS "stage_4_date_c",
  "sfdc opportunities"."stage_5_date_c" AS "stage_5_date_c",
  "sfdc opportunities"."stage_6_date_c" AS "stage_6_date_c",
  "sfdc opportunities"."stage_7_date_c" AS "stage_7_date_c",
  "sfdc opportunities"."stage_change_date_c" AS "stage_change_date_c",
  "sfdc opportunities"."stage_duration_c" AS "stage_duration_c",
  "sfdc opportunities"."stage_name" AS "stage_name",
  "sfdc opportunities"."stakeholder_identified_c" AS "stakeholder_identified_c",
  "sfdc_voc"."status_c" AS "status_c",
  "sfdc opportunities"."sub_vertical_c" AS "sub_vertical_c",
  "sfdc_voc"."system_modstamp" AS "system_modstamp",
  "sfdc opportunities"."tcp_confirmed_with_buyer_c" AS "tcp_confirmed_with_buyer_c",
  "sfdc opportunities"."tcp_customer_tech_signoff_c" AS "tcp_customer_tech_signoff_c",
  "sfdc opportunities"."tcp_end_date_c" AS "tcp_end_date_c",
  "sfdc opportunities"."tcp_entered_evaluation_status_c" AS "tcp_entered_evaluation_status_c",
  "sfdc opportunities"."tcp_entered_review_status_c" AS "tcp_entered_review_status_c",
  "sfdc opportunities"."tcp_lost_because_c" AS "tcp_lost_because_c",
  "sfdc opportunities"."tcp_products_used_c" AS "tcp_products_used_c",
  "sfdc opportunities"."tcp_risks_c" AS "tcp_risks_c",
  "sfdc opportunities"."tcp_solution_architecture_url_c" AS "tcp_solution_architecture_url_c",
  "sfdc opportunities"."tcp_solution_fit_score_c" AS "tcp_solution_fit_score_c",
  "sfdc opportunities"."tcp_solution_notes_c" AS "tcp_solution_notes_c",
  "sfdc opportunities"."tcp_start_date_c" AS "tcp_start_date_c",
  "sfdc opportunities"."tcp_status_c" AS "tcp_status_c",
  "sfdc opportunities"."tcp_tech_owner_c" AS "tcp_tech_owner_c",
  "sfdc opportunities"."technical_goals_notes_c" AS "technical_goals_notes_c",
  "sfdc opportunities"."territory_2_id" AS "territory_2_id",
  "sfdc opportunities"."total_contract_value_tcv_c" AS "total_contract_value_tcv_c",
  "sfdc opportunities"."trip_tik_created_c" AS "trip_tik_created_c",
  "sfdc opportunities"."trip_tik_url_c" AS "trip_tik_url_c",
  "sfdc opportunities"."type" AS "type",
  "sfdc opportunities"."vertical_c" AS "vertical_c",
  "sfdc opportunities"."vertical_formula_c" AS "vertical_formula_c",
  "sfdc.users"."voc_owner" AS "voc_owner",
  "sfdc opportunities"."vp_forecast_updated_manually_c" AS "vp_forecast_updated_manually_c",
  "sfdc opportunities"."weighted_arr_c" AS "weighted_arr_c",
  "sfdc_voc"."where_is_the_effort_required_c" AS "where_is_the_effort_required_c",
  "sfdc opportunities"."won_date_c" AS "won_date_c",
  "sfdc opportunities"."x18_digit_opportunity_id_c" AS "x18_digit_opportunity_id_c",
  "sfdc opportunities"."years_c" AS "years_c"
FROM (
  select *
  from 
  sfdc.voice_of_customer b
  WHERE 
  b.dt=(select max(dt) from sfdc.voice_of_customer)
) "sfdc_voc"
  INNER JOIN (
  select *
  from 
  sfdc.opportunities b
  WHERE 
  b.dt= (select max(dt) from sfdc.opportunities)
) "sfdc opportunities" ON ("sfdc_voc"."opportunity_c" = "sfdc opportunities"."id")
  LEFT JOIN (
  SELECT 
  b.name as voc_owner,
  b.id
  from 
  sfdc.users b
  WHERE 
  b.dt= (select max(dt) from sfdc.users  )
) "sfdc.users" ON ("sfdc_voc"."owner_id" = "sfdc.users"."id")
WHERE ((NOT "sfdc opportunities"."is_deleted") AND (NOT "sfdc_voc"."is_deleted"))